### ISSUE TITLE
Compiled faiss(1.5.3) by myself is much slower than yours

### ISSUE THREAD

**Issue by Boreaso** [onfido/faiss_prebuilt#7]
I am using your prebuilt faiss python package. I found that my own compiled version of faiss is much slower than yours(CPU version). I don't know what's the problem is. Cound you provide the versions of the dependent libraries and the corresponding Makefile, makefile-inc files? Tank you very much.

**Comment by orf** [comment]
All files used to build the package are in-repo. Check out https://github.com/onfido/faiss_prebuilt/blob/master/.travis.yml for the steps we use to build.

The makefiles are just the FAISS makefiles, we don't customize anything.

I'm sorry but without a lot more details I cannot really help you. You haven't specified what OS, Python version, compiler, hardware or versions of BLAS you are using. These are critical points to include when asking for help with a self-compiled package.

**Comment by Boreaso** [comment]
I am sorry, my os is ubuntu16.04(WSL), and all libraries is up to date. Python version is 3.7, compiler version is gcc. BLAS is openblas. And your faiss version is faster than the official Anaconda version(3 times faster) on my PC (Intel i7-8700 CPU) with the following test script (especially during IndexPQ search stage):

import faiss
import numpy as np

def run_test(index: faiss.Index):
    # random data
    x = np.empty([n, d], dtype=np.float32)
    faiss.float_rand(faiss.swig_ptr(x), n * d, 1)

    index_name = index.__class__.__name__

    # train
    print("%s: indexing..." % index_name)
    start = faiss.getmillisecs()
    index.train(x)
    block_size = 10 * 10000
    for i in range(n // block_size):
        print("%s: adding block %d" % (index_name, i))
        i0, i1 = i * block_size, min((i + 1) * block_size, n)
        index.add(x[i0:i1, :])
    end = faiss.getmillisecs()
    print("%s: build time %fms" % (index_name, end - start))

    # random query
    query = np.empty([nq, d], dtype=np.float32)
    faiss.float_rand(faiss.swig_ptr(query), nq * d, 2)
    res = None  

    # search
    print("%s: searching..." % index_name)
    start = faiss.getmillisecs()
    for i in range(n_searches):
        res = index.search(query, k)
    end = faiss.getmillisecs()
    print("%s: mean search time %fms" % (index_name, (end - start) / n_searches))

    if res is not None:
        print("Neighbor ids:", res[1])
        print("Distances:   ", res[0])


if __name__ == '__main__':
    n = 100 * 10000
    d = 200
    nq = 1
    k = 10
    M = 1
    n_bits = 12  
    n_searches = 100

    index_flat = faiss.IndexFlatL2(d)
    index_pq = faiss.IndexPQ(d, M, n_bits)
    index_pq.pq.verbose = True
    index_pq.pq.cp.niter = 1

    run_test(index_flat)
    run_test(index_pq)

**Comment by Boreaso** [comment]
@orf I am sorry, my os is ubuntu16.04(WSL), and all libraries is up to date. Python version is 3.7, compiler version is gcc-5.4.0. BLAS is openblas. And your faiss version is faster than the official Anaconda version(3 times faster) on my PC (Intel i7-8700 CPU) with the following test script (especially during IndexPQ search stage):
```Python
import faiss
import numpy as np

def run_test(index: faiss.Index):
# random data
x = np.empty([n, d], dtype=np.float32)
faiss.float_rand(faiss.swig_ptr(x), n * d, 1)

index_name = index.__class__.__name__

# train
print("%s: indexing..." % index_name)
start = faiss.getmillisecs()
index.train(x)
block_size = 10 * 10000
for i in range(n // block_size):
    print("%s: adding block %d" % (index_name, i))
    i0, i1 = i * block_size, min((i + 1) * block_size, n)
    index.add(x[i0:i1, :])
end = faiss.getmillisecs()
print("%s: build time %fms" % (index_name, end - start))

# random query
query = np.empty([nq, d], dtype=np.float32)
faiss.float_rand(faiss.swig_ptr(query), nq * d, 2)
res = None  

# search
print("%s: searching..." % index_name)
start = faiss.getmillisecs()
for i in range(n_searches):
    res = index.search(query, k)
end = faiss.getmillisecs()
print("%s: mean search time %fms" % (index_name, (end - start) / n_searches))

if res is not None:
    print("Neighbor ids:", res[1])
    print("Distances:   ", res[0])
if name == 'main':
n = 100 * 10000
d = 200
nq = 1
k = 10
M = 1
n_bits = 12
n_searches = 100

index_flat = faiss.IndexFlatL2(d)
index_pq = faiss.IndexPQ(d, M, n_bits)
index_pq.pq.verbose = True
index_pq.pq.cp.niter = 1

run_test(index_flat)
run_test(index_pq)
```

**Comment by orf** [comment]
Awesome! I'm happy to hear that it's faster, as to why: that's a mystery! It's likely to do with the BLAS versions or other dependencies rather than the compilation flags themselves, I'm not an expert here so I can't offer any more advice.

I'm not sure what I can do to help you any more, so I'm going to close this. If you do find out what causes the speed difference then please do let me know!
